# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: HetoAndrade.VozDigitada
PackageVersion: 1.10.0205
InstallerType: inno
InstallerLocale: pt-BR
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hetoandrade/hetoandrade.github.io/releases/download/vozdigitada-v1.10.0205/VozDigitada_Setup_v1.10.0205.exe
    InstallerSha256: C0BDBD8E4F3DC64175AB9DF4E48C894730E1C08099A4726A67E4A3043365A873
    ProductCode: "{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}_is1"
    AppsAndFeaturesEntries:
      - DisplayName: "VozDigitada versão 1.10.0205"
        Publisher: "Hetoandrade"
        ProductCode: "{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}_is1"
ManifestType: installer
ManifestVersion: 1.10.0
