# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: HetoAndrade.PrintCerto
PackageVersion: 1.10.0307
InstallerType: inno
InstallerLocale: pt-BR
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hetoandrade/hetoandrade.github.io/releases/download/printcerto-v1.10.0307/PrintCerto_Setup_v1.10.0307.exe
    InstallerSha256: A8BC0428CCB5717C32D4B1EFC97E3097F609BB7DABA62ECAAEB7DD44A300C0D1
    ProductCode: "{2D01495D-3FF9-4A5D-A475-9C4FF1778089}_is1"
    AppsAndFeaturesEntries:
      - DisplayName: "PrintCerto versão 1.10.0307"
        Publisher: "Hetoandrade"
        ProductCode: "{2D01495D-3FF9-4A5D-A475-9C4FF1778089}_is1"
ManifestType: installer
ManifestVersion: 1.10.0
